### ISSUE TITLE
Come up on one word project name

### ISSUE THREAD

**Issue by TheBloodMage** [SJSU272Lab/Fall16-Team30#8]

**Comment by TheBloodMage** [comment]
SlackBot Mechanic

**Comment by ghost** [comment]
Agreed

**Comment by TheBloodMage** [comment]
Bot Manufacturer  = BotMan

**Comment by AbhishekMadan** [comment]
ok

**Comment by TheBloodMage** [comment]
Decided among following names,
1. Design-Bot = DesiBot
2. Make A Bot = MakeABot
3. SlackBot_Mechanic
4. Bot Manufacturer = BotMan
